[package]
name = "biliget"

[package.metadata.release]
changelog = { path = "CHANGELOG.md", template = "keepachangelog" }
tag-prefix = "v"

publish = true
publish-doc = false

branch-whitelist = ["main", "master"]

commit-message = "chore(release): 发布 {{name}} 自 {{old_version}} 至 {{version}}"
